name: Deploy CloudFormation Stacks

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:

  check-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.cloudformation_role_arn }}
        aws-region: ${{ secrets.aws_region }}
    - name: Get Instagram User Access Token
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: instagram_tokenzzzzz

  deploy-instagram-user:
    runs-on: ubuntu-latest
    needs: check-secret
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.cloudformation_role_arn }}
        aws-region: ${{ secrets.aws_region }}
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: AddInstagramUser
        template: cloudformation/AddInstagramUser.yml
        no-fail-on-empty-changeset: "1"
        capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
